name: Compile & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
        varnish: ['6.0', '7.2', '7.3']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build testing containers
        run: docker-compose build --build-arg VARNISH_VERSION=${{ matrix.varnish }}

      - name: Setup test dependencies
        run: docker-compose up -d

      - name: Run unit tests
        run: go test ./...

      - name: Stop test dependencies
        run: docker-compose down
